# Generated by Django 5.1.6 on 2025-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_city_country_airport_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
