# Generated by Django 5.1.6 on 2025-04-23 04:32

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_insurance', models.DecimalField(decimal_places=2, default=1155.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_reference', models.CharField(default=api.models.generate_booking_reference, max_length=8, unique=True)),
                ('departing_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_bookings', to='api.flight')),
                ('returning_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returning_bookings', to='api.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('passenger_type', models.CharField(choices=[('AD', 'Adult'), ('CH', 'Child'), ('IN', 'Infant')], default='AD', max_length=2)),
                ('is_pwd', models.BooleanField(default=False)),
                ('go_rewards_id', models.CharField(blank=True, max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='api.booking')),
            ],
        ),
    ]
